name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install test dependencies
        run: |
          go install github.com/jstemmer/go-junit-report@latest
          go install golang.org/x/tools/cmd/goimports@latest
          go install golang.org/x/lint/golint@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run tests
        run: |
          make test | go-junit-report -set-exit-code > report.xml

      - name: Run linter
        run: |
          make lint

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: report.xml
        if: always()
